[tox]
envlist =
    py310-django{32,42}
    py{311,312}-django42
    isort
    black
    docs
skip_missing_interpreters = true

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312

[gh-actions:env]
DJANGO =
    3.2: django32
    4.2: django42

[testenv]
setenv =
    PYTHONPATH={toxinidir}
extras =
    tests
    coverage
deps =
  django32: Django~=3.2
  django42: Django~=4.2
install_command =
  python -I -m pip install {opts} --no-binary lxml {packages}
commands =
  pytest tests \
   --cov --cov-report xml:reports/coverage-{envname}.xml \
   {posargs}

[testenv:isort]
extras = tests
skipsdist = True
commands = isort --check-only --diff .

[testenv:black]
extras = tests
skipsdist = True
commands = black --check digid_eherkenning tests setup.py

[testenv:docs]
basepython=python
changedir=docs
skipsdist=true
extras =
    tests
    docs
commands=
    pytest check_sphinx.py -v \
    --tb=auto \
    {posargs}
