# Generated by Django 4.2.11 on 2024-07-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "digid_eherkenning_oidc_generics",
            "0008_digidconfig_loa_value_mapping_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="digidconfig",
            name="oidc_exempt_urls",
        ),
        migrations.RemoveField(
            model_name="digidmachtigenconfig",
            name="oidc_exempt_urls",
        ),
        migrations.RemoveField(
            model_name="eherkenningbewindvoeringconfig",
            name="oidc_exempt_urls",
        ),
        migrations.RemoveField(
            model_name="eherkenningconfig",
            name="oidc_exempt_urls",
        ),
    ]
