# Generated by Django 4.2.21 on 2025-06-27 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "digid_eherkenning_oidc_generics",
            "0009_remove_digidconfig_oidc_exempt_urls_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="DigiDConfig",
        ),
        migrations.DeleteModel(
            name="DigiDMachtigenConfig",
        ),
        migrations.DeleteModel(
            name="EHerkenningBewindvoeringConfig",
        ),
        migrations.DeleteModel(
            name="EHerkenningConfig",
        ),
    ]
