# Generated by Django 5.2 on 2025-07-24 13:51

from django.db import migrations

from digid_eherkenning.oidc.migrations_operations import (
    MoveDigiDDataOperation,
    MoveDigiDMachtigenDataOperation,
    MoveEHerkenningBewindvoeringDataOperation,
    MoveEHerkenningDataOperation,
)


class Migration(migrations.Migration):
    dependencies = [
        ("oidc_project", "0001_initial"),
        (
            "mozilla_django_oidc_db",
            "0006_oidcprovider_oidcclient",
        ),
        (
            "digid_eherkenning_oidc_generics",
            "0009_remove_digidconfig_oidc_exempt_urls_and_more",
        ),
    ]
    run_before = [
        (
            "digid_eherkenning_oidc_generics",
            "0010_delete_digidconfig_delete_digidmachtigenconfig_and_more",
        ),
        ("mozilla_django_oidc_db", "0008_delete_openidconnectconfig"),
    ]

    operations = [
        MoveDigiDDataOperation("oidc-digid-config"),
        MoveDigiDMachtigenDataOperation("oidc-digid-machtigen-config"),
        MoveEHerkenningDataOperation("oidc-eh-config"),
        MoveEHerkenningBewindvoeringDataOperation("oidc-eh-bewindvoering-config"),
    ]
