# Generated by Django 3.2.15 on 2022-10-27 13:05

import django.contrib.auth.models
from django.db import migrations, models

import djchoices.choices


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="login_type",
            field=models.CharField(
                choices=[("digid", "DigiD"), ("eherkenning", "eHerkenning")],
                max_length=20,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {"digid": "DigiD", "eherkenning": "eHerkenning"}
                    )
                ],
            ),
        ),
    ]
