# Generated by Django 3.2.15 on 2022-08-29 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("simple_certmanager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EherkenningMetadataConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "want_assertions_signed",
                    models.BooleanField(
                        default=True,
                        help_text="If True, the XML assertions need to be signed, otherwise the whole response needs to be signed.",
                        max_length=100,
                        verbose_name="Want assertions signed",
                    ),
                ),
                (
                    "want_assertions_encrypted",
                    models.BooleanField(
                        default=False,
                        help_text="If True the XML assertions need to be encrypted.",
                        max_length=100,
                        verbose_name="Want assertions encrypted",
                    ),
                ),
                (
                    "key_passphrase",
                    models.CharField(
                        blank=True,
                        help_text="Passphrase for SOAP client",
                        max_length=100,
                        verbose_name="Key passphrase",
                    ),
                ),
                (
                    "signature_algorithm",
                    models.CharField(
                        blank=True,
                        default="http://www.w3.org/2000/09/xmldsig#rsa-sha1",
                        help_text="Signature algorithm",
                        max_length=100,
                        verbose_name="Signature algorithm",
                    ),
                ),
                (
                    "digest_algorithm",
                    models.CharField(
                        blank=True,
                        default="http://www.w3.org/2000/09/xmldsig#sha1",
                        help_text="Digest algorithm",
                        max_length=100,
                        verbose_name="Digest algorithm",
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        help_text="Service provider entity ID",
                        max_length=100,
                        verbose_name="Entity ID",
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        help_text="Base URL of the application",
                        max_length=100,
                        verbose_name="Base URL",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        help_text="The name of the service for which DigiD login is required",
                        max_length=100,
                        verbose_name="Service name",
                    ),
                ),
                (
                    "service_description",
                    models.CharField(
                        help_text="A description of the service for which DigiD login is required",
                        max_length=100,
                        verbose_name="Service description",
                    ),
                ),
                (
                    "technical_contact_person_telephone",
                    models.CharField(
                        blank=True,
                        help_text="Telephone number of the technical person responsible for this DigiD setup. For it to be used, technical_contact_person_email should also be set.",
                        max_length=100,
                        verbose_name="Technical contact person telephone",
                    ),
                ),
                (
                    "technical_contact_person_email",
                    models.CharField(
                        blank=True,
                        help_text="Email address of the technical person responsible for this DigiD setup. For it to be used, technical_contact_person_telephone should also be set.",
                        max_length=100,
                        verbose_name="Technical contact person email",
                    ),
                ),
                (
                    "organization_url",
                    models.URLField(
                        blank=True,
                        help_text="URL of the organisation providing the service for which DigiD login is setup. For it to be used, also organization_name should be filled.",
                        max_length=100,
                        verbose_name="Organization URL",
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the organisation providing the service for which DigiD login is setup. For it to be used, also organization_url should be filled",
                        max_length=100,
                        verbose_name="Organization name",
                    ),
                ),
                (
                    "attribute_consuming_service_index",
                    models.CharField(
                        blank=True,
                        default="1",
                        help_text="Attribute consuming service index",
                        max_length=100,
                        verbose_name="Attribute consuming service index",
                    ),
                ),
                (
                    "loa",
                    models.CharField(
                        blank=True,
                        default="urn:etoegang:core:assurance-class:loa3",
                        help_text="Level of Assurance (LoA) to use for all the services.",
                        max_length=100,
                        verbose_name="Loa",
                    ),
                ),
                (
                    "eh_attribute_consuming_service_index",
                    models.CharField(
                        blank=True,
                        default="9052",
                        help_text="Attribute consuming service index for the eHerkenning service",
                        max_length=100,
                        verbose_name="eh attribute consumng service index",
                    ),
                ),
                (
                    "eidas_attribute_consuming_service_index",
                    models.CharField(
                        blank=True,
                        default="9053",
                        help_text="Attribute consuming service index for the eHerkenning service",
                        max_length=100,
                        verbose_name="eidas attribute consumng service index",
                    ),
                ),
                (
                    "oin",
                    models.CharField(
                        help_text="The OIN of the company providing the service.",
                        max_length=100,
                        verbose_name="Oin",
                    ),
                ),
                (
                    "no_eidas",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="If True, then the service catalogue will contain only the eHerkenning service.",
                        verbose_name="No eidas",
                    ),
                ),
                (
                    "privacy_policy",
                    models.URLField(
                        help_text="The URL where the privacy policy from the organisation providing the service can be found.",
                        max_length=100,
                        verbose_name="Privacy policy",
                    ),
                ),
                (
                    "makelaar_id",
                    models.CharField(
                        help_text="OIN of the broker used to set up eHerkenning/eIDAS.",
                        max_length=100,
                        verbose_name="Makelaar ID",
                    ),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="simple_certmanager.certificate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Eherkenning metadata configuration",
            },
        ),
        migrations.CreateModel(
            name="DigidMetadataConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "want_assertions_signed",
                    models.BooleanField(
                        default=True,
                        help_text="If True, the XML assertions need to be signed, otherwise the whole response needs to be signed.",
                        max_length=100,
                        verbose_name="Want assertions signed",
                    ),
                ),
                (
                    "want_assertions_encrypted",
                    models.BooleanField(
                        default=False,
                        help_text="If True the XML assertions need to be encrypted.",
                        max_length=100,
                        verbose_name="Want assertions encrypted",
                    ),
                ),
                (
                    "key_passphrase",
                    models.CharField(
                        blank=True,
                        help_text="Passphrase for SOAP client",
                        max_length=100,
                        verbose_name="Key passphrase",
                    ),
                ),
                (
                    "signature_algorithm",
                    models.CharField(
                        blank=True,
                        default="http://www.w3.org/2000/09/xmldsig#rsa-sha1",
                        help_text="Signature algorithm",
                        max_length=100,
                        verbose_name="Signature algorithm",
                    ),
                ),
                (
                    "digest_algorithm",
                    models.CharField(
                        blank=True,
                        default="http://www.w3.org/2000/09/xmldsig#sha1",
                        help_text="Digest algorithm",
                        max_length=100,
                        verbose_name="Digest algorithm",
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        help_text="Service provider entity ID",
                        max_length=100,
                        verbose_name="Entity ID",
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        help_text="Base URL of the application",
                        max_length=100,
                        verbose_name="Base URL",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        help_text="The name of the service for which DigiD login is required",
                        max_length=100,
                        verbose_name="Service name",
                    ),
                ),
                (
                    "service_description",
                    models.CharField(
                        help_text="A description of the service for which DigiD login is required",
                        max_length=100,
                        verbose_name="Service description",
                    ),
                ),
                (
                    "technical_contact_person_telephone",
                    models.CharField(
                        blank=True,
                        help_text="Telephone number of the technical person responsible for this DigiD setup. For it to be used, technical_contact_person_email should also be set.",
                        max_length=100,
                        verbose_name="Technical contact person telephone",
                    ),
                ),
                (
                    "technical_contact_person_email",
                    models.CharField(
                        blank=True,
                        help_text="Email address of the technical person responsible for this DigiD setup. For it to be used, technical_contact_person_telephone should also be set.",
                        max_length=100,
                        verbose_name="Technical contact person email",
                    ),
                ),
                (
                    "organization_url",
                    models.URLField(
                        blank=True,
                        help_text="URL of the organisation providing the service for which DigiD login is setup. For it to be used, also organization_name should be filled.",
                        max_length=100,
                        verbose_name="Organization URL",
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the organisation providing the service for which DigiD login is setup. For it to be used, also organization_url should be filled",
                        max_length=100,
                        verbose_name="Organization name",
                    ),
                ),
                (
                    "attribute_consuming_service_index",
                    models.CharField(
                        blank=True,
                        default="1",
                        help_text="Attribute consuming service index",
                        max_length=100,
                        verbose_name="Attribute consuming service index",
                    ),
                ),
                (
                    "slo",
                    models.BooleanField(
                        default=True,
                        help_text="If enabled, Single Logout is supported",
                        verbose_name="Single logout",
                    ),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="simple_certmanager.certificate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Digid metadata configuration",
            },
        ),
    ]
