# Generated by Django 4.2.18 on 2025-03-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digid_eherkenning", "0001_initial_to_v019"),
    ]

    operations = [
        migrations.CreateModel(
            name="MockDigidUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the mock user.", max_length=50),
                ),
                ("bsn", models.IntegerField(help_text="Burgerservicenummer")),
            ],
        ),
    ]
