# Generated by Django 3.2.15 on 2022-09-07 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simple_certmanager", "0001_initial"),
        ("digid_eherkenning", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digidmetadataconfiguration",
            name="certificate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="simple_certmanager.certificate",
            ),
        ),
        migrations.AlterField(
            model_name="eherkenningmetadataconfiguration",
            name="certificate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="simple_certmanager.certificate",
            ),
        ),
    ]
