# Generated by Django 4.2.18 on 2025-03-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("digid_eherkenning", "0002_mockdigiduser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mockdigiduser",
            options={"verbose_name": "Mock DigiD user"},
        ),
    ]
