# Generated by Django 3.2.15 on 2022-10-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digid_eherkenning", "0003_auto_20221020_1029"),
    ]

    operations = [
        migrations.AddField(
            model_name="eherkenningmetadataconfiguration",
            name="artifact_resolve_content_type",
            field=models.CharField(
                default="application/soap+xml",
                max_length=100,
                verbose_name="resolve artifact binding content type",
            ),
        ),
    ]
