# Generated by Django 4.2.20 on 2025-03-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("digid_eherkenning", "0003_alter_mockdigiduser_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mockdigiduser",
            name="bsn",
            field=models.CharField(help_text="Burgerservicenummer", max_length=9),
        ),
    ]
