# Generated by Django 5.1.7 on 2025-07-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("digid_eherkenning", "0004_alter_mockdigiduser_bsn"),
    ]

    operations = [
        migrations.AddField(
            model_name="configcertificate",
            name="activate_on",
            field=models.DateTimeField(
                blank=True,
                help_text="The date on which the certificate becomes active. This is required in order to synchronize the switching of certificates with the IdP.",
                null=True,
                verbose_name="activation date",
            ),
        ),
    ]
