# Generated by Django 3.2.15 on 2022-10-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "digid_eherkenning",
            "0004_eherkenningmetadataconfiguration_artifact_resolve_content_type",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="eherkenningmetadataconfiguration",
            name="eh_service_language",
            field=models.CharField(
                default="nl", max_length=2, verbose_name="eHerkenning service language"
            ),
        ),
        migrations.AddField(
            model_name="eherkenningmetadataconfiguration",
            name="eidas_service_language",
            field=models.CharField(
                default="nl", max_length=2, verbose_name="eidas service language"
            ),
        ),
    ]
