# Generated by Django 5.2.14 on 2026-05-15 20:59

from django.db import migrations

import privates.fields


class Migration(migrations.Migration):
    dependencies = [
        ("digid_eherkenning", "0005_configcertificate_activation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digidconfiguration",
            name="idp_metadata_file",
            field=privates.fields.PrivateMediaFileField(
                blank=True,
                help_text="The metadata file of the identity provider. This is auto populated from the configured source URL.",
                upload_to="",
                verbose_name="identity provider metadata",
            ),
        ),
        migrations.AlterField(
            model_name="eherkenningconfiguration",
            name="idp_metadata_file",
            field=privates.fields.PrivateMediaFileField(
                blank=True,
                help_text="The metadata file of the identity provider. This is auto populated from the configured source URL.",
                upload_to="",
                verbose_name="identity provider metadata",
            ),
        ),
    ]
