# Generated by Django 3.2.15 on 2022-10-21 14:05

from django.db import migrations, models

import digid_eherkenning.models.digid_metadata_config


class Migration(migrations.Migration):

    dependencies = [
        ("digid_eherkenning", "0006_auto_20221021_0911"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eherkenningmetadataconfiguration",
            name="attribute_consuming_service_index",
        ),
        migrations.AlterField(
            model_name="digidmetadataconfiguration",
            name="requested_attributes",
            field=models.JSONField(
                default=digid_eherkenning.models.digid_metadata_config.default_digid_requested_attributes,
                help_text="A list of strings (or objects) with the requested attributes, e.g. '[\"bsn\"]'",
                verbose_name="requested attributes",
            ),
        ),
    ]
