# Generated by Django 4.2.10 on 2024-03-07 16:49

import digid_eherkenning.models.eherkenning
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digid_eherkenning", "0007_eherkenningconfiguration_service_description_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eherkenningconfiguration",
            name="eh_requested_attributes",
            field=models.JSONField(
                default=digid_eherkenning.models.eherkenning.get_default_requested_attributes_eherkenning,
                help_text="A list of additional requested attributes. A single requested attribute can be a string (the name of the attribute) or an object with keys 'name' and 'required', where 'name' is a string and 'required' a boolean'.",
                verbose_name="requested attributes",
            ),
        ),
        migrations.AlterField(
            model_name="eherkenningconfiguration",
            name="eidas_requested_attributes",
            field=models.JSONField(
                default=digid_eherkenning.models.eherkenning.get_default_requested_attributes_eidas,
                help_text="A list of additional requested attributes. A single requested attribute can be a string (the name of the attribute) or an object with keys 'name' and 'required', where 'name' is a string and 'required' a boolean'.",
                verbose_name="requested attributes",
            ),
        ),
    ]
