# Generated by Django 4.2.13 on 2024-07-18 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("digid_eherkenning", "0008_update_loa_fields"),
    ]

    operations = []
