# Generated by Django 4.2.13 on 2024-07-19 12:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "digid_eherkenning",
            "0011_configcertificate_configcertificate_uniq_config_cert",
        ),
    ]

    operations = [
        # RunPython operation was removed as part of 0.20 release cycle
        migrations.RemoveField(
            model_name="digidconfiguration",
            name="certificate",
        ),
        migrations.RemoveField(
            model_name="eherkenningconfiguration",
            name="certificate",
        ),
    ]
