# Generated by Django 4.2.13 on 2025-01-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "digid_eherkenning",
            "0015_digidconfiguration_administrative_contact_person_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="eherkenningconfiguration",
            name="eidas_service_description",
            field=models.CharField(
                blank=True,
                help_text="A description of the service you are providing. If left blank, the eHerkenning description is re-used.",
                max_length=100,
                verbose_name="service description (eIDAS)",
            ),
        ),
    ]
